### ISSUE TITLE
jq: parse error

### ISSUE THREAD

**Issue by salvatorec19** [amckee23/home-assistant-hypon-cloud#6]
I installed the add-on in Home Assistant without any problems, in the configuration I entered the user, password and device ID, and after turning it on I get the following logs:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:08:07] INFO: Loading Authentication Token
[08:08:07] INFO: Login Start
[08:08:08] INFO: Login End
[08:08:08] INFO: Load Solar Data Start
[08:08:08] INFO: Load Solar Data End
[08:08:08] INFO: Load Realtime Start
[08:08:08] INFO: Load Realtime Data End
jq: parse error: Invalid numeric literal at line 1, column 7
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by tradosh** [comment]
just look here: https://github.com/amckee23/home-assistant-hypon-cloud/pull/11/files this is what I changed, so you just put that change to your local code and compile and it should be fine

**Comment by MarjanArtac** [comment]
I installed it via add-on. I will wait for the update when it is available. Thanks for the response.

**Comment by tradosh** [comment]
in that case install terminal on your home assistnat - then using commands do the following:
cd addons/hypon-cloud/scripts
vim hypon.sh (or nano hypon.sh)
update the lines based on the changes from my code.
once completed go to addon and on hyponcloud addon select rebuild and it should start withthe updated config

**Comment by MarjanArtac** [comment]
And this is the biggest problem, because I can't find anywhere where the addon is installed. I get the error:
[core-ssh /]$ cd addons/hypon-cloud/scripts
-bash: cd: addons/hypon-cloud/scripts: No such file or directory

**Comment by amckee23** [comment]
I have pushed some changes based on the PR from @tradosh  If you uninstall the plugin, remove the plugin from the pluginstore and reinstall version 1.1.1 it should work now

**Comment by MarjanArtac** [comment]
I installed version 1.1.1, but after starting I still get the same error in the logs:
[12:58:13] INFO: Loading Authentication Token
[12:58:14] INFO: Login Start
[12:58:14] INFO: Login End
[12:58:14] INFO: Load Solar Data Start
[12:58:14] INFO: Load Solar Data End
[12:58:14] INFO: Load Realtime Start
[12:58:15] INFO: Load Realtime Data End
[12:58:15] ERROR: Data Retrieval Error - updating auth token
[12:58:15] INFO: Login Start
[12:58:15] INFO: Login End

**Comment by tradosh** [comment]
@MarjanArtac you would have to remove the old addon, pull the latest updates, and then make sure it's 1.1.1

**Comment by MarjanArtac** [comment]
I uninstalled v.1.1.1 again, restarted HA and reinstalled Hypon Cloud v.1.1.1 and I still get the error in the log file:
[15:30:29] INFO: Loading Authentication Token
[15:30:29] INFO: Login Start
[15:30:30] INFO: Login End
[15:30:30] INFO: Load Solar Data Start
[15:30:30] INFO: Load Solar Data End
[15:30:30] INFO: Load Realtime Start
[15:30:30] INFO: Load Realtime Data End
[15:30:31] ERROR: Data Retrieval Error - updating auth token
[15:30:31] INFO: Login Start
[15:30:31] INFO: Login End

**Comment by ImS-51100** [comment]
> I uninstalled v.1.1.1 again, restarted HA and reinstalled Hypon Cloud v.1.1.1 and I still get the error in the log file: [15:30:29] INFO: Loading Authentication Token [15:30:29] INFO: Login Start [15:30:30] INFO: Login End [15:30:30] INFO: Load Solar Data Start [15:30:30] INFO: Load Solar Data End [15:30:30] INFO: Load Realtime Start [15:30:30] INFO: Load Realtime Data End [15:30:31] ERROR: Data Retrieval Error - updating auth token [15:30:31] INFO: Login Start [15:30:31] INFO: Login End

J'ai eu le meme soucis que vous. Le probleme vennais du system_id.

Il faut bien prendre celui dqns les parametres de l'application  (parametre > profil du compte > ID de compte ) et non celui du micro onduleur qui commence par la lettre P.

Je suis désolé.. je parle pas anglais.

**Comment by MarjanArtac** [comment]
Merci pour l'idée, mais malheureusement je n'utilise plus l'appareil Hyponclud. Je suis passé à Envertech et je ne peux pas tester son fonctionnement.

Malheureusement, je ne parle pas français non plus, mais j'ai utilisé Google Traduction.

**Comment by CyC-Innovation** [comment]
Hello,

I have the same problem.
I am currently running version 1.1.1.

Although the watchdog is enabled, the script does not restart automatically after it stops because of the error shown below.

jq: parse error: Invalid numeric literal at line 1, column 7
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

**Comment by Terry-JF** [comment]
Hi CyC-Innovation,

I had this same issue last week when setting this app up within Homeassistant. I was trying to use incorrect details in the configuration and so the app fails to validate when it tries to logon to the Hypon.cloud webserver. I assume that you already have the hypon.cloud app setup on your phone or else via a web browser session from your PC, if not do that first to verify you can connect to hypon.cloud and see your inverter. Once that is working, go to settings in the hypon.cloud app/pc (gear wheel) and you will see your system ID. Use the logon details (username + password) you have created to logon to the hypon.cloud app on your phone/pc plus the System ID and enter these into the configuration tab in the hypon.cloud addon within homeassistant. Restart, then check the log (rightmost tab) to verify that it has connected to the hypon.cloud service OK.

Good luck, Terry
